### PR TITLE
Custom forks for sickrage

### PR DESCRIPTION
**Pull request by bbsan2k**
[linuxserver.io](https://linuxserver.io)

Added the possibility of declaring a custom FORK through env variable ($FORK)

### CODE REVIEW

**Comment by sparklyballs** [comment]
This is not something we would be looking to implement, we are listed as an install source for the fork we currently use, https://github.com/SickRage/SickRage/wiki/Sickrage-installation-packages#docker

**Comment by bbsan2k** [comment]
Can you maybe explain a little more? My modification actually does not change any behavior, if env FORK is not set manually. sickrage/sickrage will be installed without any problems with this PR

**Comment by CHBMB** [comment]
Well, we are their listed docker provider, how would you feel if you were them and we started offering "competing" images? Using their listed docker container.  Bit below the belt.

**Comment by bbsan2k** [comment]
Hmmm understandable concern, but too bad they don't offer multi language to the full extend...

**Pull request closed without merging**
