### PR TITLE
Get submodules

### PR DESCRIPTION
**Pull request by zaggash**
Hello,

Here is the PR to be able to use nzbtomedia to directly send a post process request to sickrage.

Maybe /app is too widly open, tell me about it, how do you think to manage this volume ?

### CODE REVIEW

**Comment by sparklyballs** [comment]
i'm not dismissing this out of hand, but i want to speak to one of the sickrage devs first before proceeding.

**Comment by lonix** [comment]
@zaggash Im currently talking to authors, and will get back to you "shortly"

**Comment by pecigonzalo** [comment]
BTW this also needs to be rebased

**Comment by zaggash** [comment]
Done

**Comment by zaggash** [comment]
Any feedback from the talk ?

**Comment by sparklyballs** [comment]
i think it's stalled a bit there. 

tbh i don't what know this does, and therefore what effect it could have on the container as a whole.

**Comment by zaggash** [comment]
Actually this have no impact on the container.
Since this will just pull the submodule.

The tool is here to add more feature on moving, transcoding,... downloaded files.
ffmpeg is required to allow the transoding.
It works with Sickrage, CP, and a lot more.

It act as a python script, it must be called by the torrent daemon as an extra script.

**Comment by sparklyballs** [comment]
@zaggash can you rebase and i'll merge after lunch

**Comment by zaggash** [comment]
Just thinking but we can add an environment variable to give the user a choice to add or not this set of scripts.

Because, if we want to add it correctly, I would like to add more packages ( ffmpeg, p7zip ) add a new volume ( /nzb2media ) with a link to the script and config file.

Or we can think to create a dedicated container, which may be the better thngs to do.
Because it can be used with others applications than Sickrage.

**Comment by zaggash** [comment]
#3

**Comment by sparklyballs** [comment]
https://github.com/linuxserver/docker-sickrage/pull/4#issuecomment-180359964

i think developing mp4automator container may be a better way forward with this.

we can put all the dependencies into that..

**Pull request closed without merging**
